apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: api
spec:
  containers:
  - name: api
    image: bjesua/api-go  # Cambia esto por el nombre de tu imagen
    env:
    - name: SECRET_KEY
      value: "Tribal_Token"
    - name: PATH_APPLE
      value: "https://itunes.apple.com/search?term="
    - name: CHARTLYRICS_API
      value: "http://api.chartlyrics.com/apiv1.asmx/SearchLyric?artist="
    - name: DB_HOST
      value: "mysql-service"
    - name: DB_USER
      value: "user"
    - name: DB_PASSWORD
      value: "password"
    - name: DB_NAME
      value: "database"
    ports:
    - containerPort: 8081
  volumes:
  - name: api-volume
    # hostPath:
    #   path: /mnt/api  # Ruta en el host
    #   type: Directory
